# Generated by Django 3.2.12 on 2022-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220326_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='nothing', help_text='max 150 символов', max_length=150, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
