# Generated by Django 3.2.12 on 2022-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='default_category_name', help_text='max 150 символов', max_length=150, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
